[package]
name = "hashmap"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[profile.release]
codegen-units = 1
lto = "fat"
strip = true
panic = "abort"

[lib]
crate-type = ["staticlib"]

[dependencies]
byte-strings = "0.2.2"
phf = "0.11"

[build-dependencies]
phf_codegen = "0.11"
